apps/pegasus/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers

from . import views

app_name = 'pegasus'

urlpatterns = [
    path(r'', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path(r'<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
    path(r'payments', views.PaymentView.as_view(), name='payments'),
#     path(r'payments/create_payment_intent/', views.create_payment_intent, name='create_payment_intent'),
#     path(r'payments/create/', views.accept_payment, name='accept_payment'),
#     path(r'payments/confirm/<slug:payment_id>/', views.payment_confirm, name='payment_confirm'),
#     path(r'landing_page/', TemplateView.as_view(template_name='pegasus/examples/example_landing_page.html'),
#          name='landing_page'),
#     path(r'pricing_page/', TemplateView.as_view(template_name='pegasus/examples/example_pricing_page.html'),
#          name='pricing_page'),
#     path(r'objects/react/', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle'),
#     path(r'objects/react/<path:path>', views.ReactObjectLifecycleView.as_view(), name='react_object_lifecycle_w_path'),
#     path(r'objects/vue/', views.VueObjectLifecycleView.as_view(), name='vue_object_lifecycle'),
#     path(r'charts/', views.ChartsView.as_view(), name='charts'),
#     path(r'tasks/', views.TasksView.as_view(), name='tasks'),
#     path(r'tasks/api/', views.tasks_api, name='tasks_api'),

#     path(r'api/employee-data/', views.EmployeeDataAPIView.as_view(), name='employee_data'),
]


# drf config
router = routers.DefaultRouter()
router.register(r'api/employees', views.EmployeeViewSet)

urlpatterns += router.urls

mail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('unsubscribes/', include('apps.unsubscribes.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('campaignschedule/',include('apps.campaignschedule.urls')),
    path('campaign/', include('apps.campaign.urls')),
    path('teams/', include('apps.teams.urls')),
    path('intigration/', include('apps.integration.urls')),
    path('mail/', include('apps.mailaccounts.urls')),
    path('', include('apps.web.urls')),
    path('app/', include('apps.pegasus.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pegasus/models/objects.py
from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Employee(BaseModel):
    DEPARTMENT_CHOICES = (
        ('hr', 'Human Resources'),
        ('finance', 'Finance'),
        ('engineering', 'Engineering'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employees')
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=20, choices=DEPARTMENT_CHOICES)
    salary = models.PositiveIntegerField()

    def __str__(self):
        return self.name

apps/pegasus/models/payments.py
import uuid

from django.conf import settings
from django.db import models

from apps.utils.models import BaseModel


class Payment(BaseModel):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    charge_id = models.CharField(max_length=100, help_text='The stripe charge ID associated with this payment.')
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pegasus_payments')
    amount = models.PositiveIntegerField(help_text='In cents')

    @property
    def payment_id(self):
        return str(self.id)

    @property
    def amount_display(self):
        return '${:,.2f}'.format(self.amount / 100.)

apps/pegasus/views/objects.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Sum, Count
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from ..models import Employee
from ..serializers import EmployeeSerializer


# @method_decorator(login_required, name='dispatch')
class ObjectLifecycleView(TemplateView):
    def get_context_data(self, **kwargs):
        return {
            'department_choices': [{
                'id': c[0],
                'name': c[1]
            } for c in Employee.DEPARTMENT_CHOICES],
        }


class ReactObjectLifecycleView(ObjectLifecycleView):
    template_name = 'pegasus/objects/react_object_lifecycle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'framework_url': 'https://reactjs.org/',
            'framework_name': 'React',
            'framework_icon': static('images/pegasus/react-icon.png'),
            'active_tab': 'react_object_lifecycle',
        })
        return context


class EmployeeDataAPIView(APIView):

    def get(self, request):
        data = request.user.employees.values('department').annotate(
            average_salary=Avg('salary'),
            total_cost=Sum('salary'),
            number_employees=Count('pk'),
        )
        # data will look something like this:
        # [
        #     {'total_cost': 132000, 'number_employees': 2, 'average_salary': 66000.0, 'department': 'hr'},
        #     {'total_cost': 60000, 'number_employees': 1, 'average_salary': 60000.0, 'department': 'marketing'}
        # ]
        total_costs = [
            [row['department'], row['total_cost']] for row in data
        ]
        average_salaries = [
            [row['department'], row['average_salary']] for row in data
        ]
        headcounts = [
            [row['department'], row['number_employees']] for row in data
        ]
        return Response({
            'total_costs': total_costs,
            'average_salaries': average_salaries,
            'headcounts': headcounts,
        })


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.employees.all()

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

apps/pegasus/views/payments.py
import json

import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from apps.utils.decorators import catch_stripe_errors
from ..models import Payment

EXPECTED_PAYMENT_AMOUNT = 2500  # in cents

@method_decorator(login_required, name='dispatch')
class PaymentView(TemplateView):
    template_name = 'pegasus/payments/payments.html'

    def get_context_data(self, **kwargs):
        return {
            'stripe_key': settings.STRIPE_TEST_PUBLIC_KEY,
            'payments': self.request.user.pegasus_payments.all(),
            'amount': EXPECTED_PAYMENT_AMOUNT,
            'active_tab': 'payments',
        }


@login_required
@require_POST
def create_payment_intent(request):
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=2500,  # in cents
        currency='usd',
        description=f'A Demo Payment',
    )
    return JsonResponse({
        'client_secret': intent['client_secret'],
    })


@login_required
def payment_confirm(request, payment_id):
    """
    Confirmation page after making a payment.
    """
    payment = get_object_or_404(Payment, user=request.user, id=payment_id)
    return render(request, 'pegasus/payments/payment_confirm.html', {
        'payment': payment,
        'active_tab': 'payments',
    })


@login_required
@require_POST
def accept_payment(request):
    """
    Accept a payment with a token from Stripe
    """
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    name = request.POST['name']
    payment_intent_id = request.POST['paymentIntent']
    payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
    if payment_intent.status != 'succeeded':
        raise Exception(f'Unexpected payment intent status: {payment_intent.status}')

    amount = payment_intent['amount']
    if amount != EXPECTED_PAYMENT_AMOUNT:
        raise ValueError(f'Unexpected payment amount {payment_intent["amount"]}')

    charge = payment_intent['charges']['data'][0]

    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY
    user = request.user
    payment = Payment.objects.create(
        charge_id=charge.id,
        amount=charge.amount,
        name=name,
        user=user,
    )
    return HttpResponseRedirect(reverse('pegasus:payment_confirm', args=[payment.payment_id]))

apps/pegasus/views/tasks.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

# from ..tasks import progress_bar_task


@method_decorator(login_required, name='dispatch')
class TasksView(TemplateView):
    template_name = 'pegasus/tasks.html'

    def get_context_data(self, **kwargs):
        return {
            'active_tab': 'tasks',
        }


# @require_POST
# def tasks_api(request):
#     result = progress_bar_task.delay(5)
#     return HttpResponse(result.task_id)

templates/pegasus/components/examples_nav.html
<aside class="menu">
  <p class="menu-label is-hidden-tablet-only">
    Pegasus
  </p>
  <ul class="menu-list">
      {% comment %} <li>
          <a href="{% url 'pegasus:react_object_lifecycle' %}" {% if active_tab == 'home' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-home"></i></span><span class="is-hidden-tablet-only">Examples Home</span>
          </a>
      </li>
      <li>
          <a href="{% url 'pegasus:payments' %}" {% if active_tab == 'payments' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-credit-card"></i></span><span class="is-hidden-tablet-only">Payments</span>
          </a>
      </li> {% endcomment %}
      <li>
          <a href="{% url 'pegasus:react_object_lifecycle' %}" {% if active_tab == 'react_object_lifecycle' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-edit"></i></span><span class="is-hidden-tablet-only">React Object Demo</span>
          </a>
      </li>
      {% comment %} <li>
          <a href="{% url 'pegasus:tasks' %}" {% if active_tab == 'tasks' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-tasks"></i></span><span class="is-hidden-tablet-only">Background Tasks</span>
          </a>
      </li> {% endcomment %}
      {% comment %} <li>
          <a href="{% url 'pegasus:charts' %}" {% if active_tab == 'charts' %}class="is-active"{% endif %}>
              <span class="icon"><i class="fa fa-bar-chart-o"></i></span><span class="is-hidden-tablet-only">Charts</span>
          </a>
      </li>
      <li>
          <a href="{% url 'pegasus:landing_page' %}" >
              <span class="icon"><i class="fa fa-picture-o"></i></span><span class="is-hidden-tablet-only">Landing Page</span>
          </a>
      </li>
      <li>
          <a href="{% url 'pegasus:pricing_page' %}" >
              <span class="icon"><i class="fa fa-external-link"></i></span><span class="is-hidden-tablet-only">Pricing Page</span>
          </a>
      </li> {% endcomment %}
  </ul>
</aside>

templates/pegasus/components/sticky-header-js.html
<script type="application/javascript">
    // sticky header - see https://coder-coder.com/sticky-header-animated/ for details
    var checkHeader = function () {
        var scrollPosition = Math.round(window.scrollY);
        if (scrollPosition > 52){
            document.querySelector('.app-notice').classList.add('sticky');
            document.querySelector('#example-page-content').classList.add('sticky-offset');
        }
        // If not, remove "sticky" class from header
        else {
            document.querySelector('.app-notice').classList.remove('sticky');
            document.querySelector('#example-page-content').classList.remove('sticky-offset');
        }
    };
    window.addEventListener('scroll', checkHeader);
</script>