apps/teams/urls.py
from django.urls import path
from . import views

from rest_framework import routers


app_name = 'teams'

urlpatterns = [
    path('', views.manage_teams, name='manage_teams'),
    path('list/', views.list_teams, name='list_teams'),
    path('create/', views.create_team, name='create_team'),
    path('<slug:team_slug>/manage/', views.manage_team, name='manage_team'),
    path('<slug:team_slug>/resend-invite/<slug:invitation_id>/', views.resend_invitation,
         name='resend_invitation'),
    path('invitation/<slug:invitation_id>/', views.accept_invitation, name='accept_invitation'),
    path('invitation/<slug:invitation_id>/confirm/', views.accept_invitation_confirm,
         name='accept_invitation_confirm'),
]

# drf config
router = routers.DefaultRouter()
router.register(r'api/teams', views.TeamViewSet)
router.register(r'api/invitations', views.InvitationViewSet)
urlpatterns += router.urls

mail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls, get_schemajs_view


schemajs_view = get_schemajs_view(title="API")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('apps.users.urls')),
    path('unsubscribes/', include('apps.unsubscribes.urls')),
    path('subscriptions/', include('apps.subscriptions.urls')),
    path('campaignschedule/',include('apps.campaignschedule.urls')),
    path('campaign/', include('apps.campaign.urls')),
    path('teams/', include('apps.teams.urls')),
    path('intigration/', include('apps.integration.urls')),
    path('mail/', include('apps.mailaccounts.urls')),
    path('', include('apps.web.urls')),
    path('app/', include('apps.pegasus.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    # API docs
    # these are needed for schema.js
    path('docs/', include_docs_urls(title='API Docs')),
    path('schemajs/', schemajs_view, name='api_schemajs'),

    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/teams/models.py
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from apps.subscriptions.helpers import SubscriptionModelMixin
from apps.utils.models import BaseModel


from apps.web.meta import absolute_url

from . import roles


class Team(SubscriptionModelMixin, BaseModel):
    """
    A Team, with members.
    """
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    subscription = models.ForeignKey('djstripe.Subscription', null=True, blank=True, on_delete=models.SET_NULL,
                                     help_text=_("The team's Stripe Subscription object, if it exists"))

    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='teams', through='Membership')
    # your team customizations go here.

    def __str__(self):
        return self.name

    @property
    def sorted_memberships(self):
        return self.membership_set.order_by('user__email')

    def pending_invitations(self):
        return self.invitations.filter(is_accepted=False)

    @property
    def dashboard_url(self):
        return reverse('web:team_home', args=[self.slug])


class Membership(BaseModel):
    """
    A user's team membership
    """
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, choices=roles.ROLE_CHOICES)
    # your additional membership fields go here.


class Invitation(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='invitations')
    email = models.EmailField()
    role = models.CharField(max_length=100, choices=roles.ROLE_CHOICES, default=roles.ROLE_MEMBER)
    invited_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                   related_name='sent_invitations')
    is_accepted = models.BooleanField(default=False)
    accepted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                    related_name='accepted_invitations', null=True, blank=True)

    def get_url(self):
        return absolute_url(reverse('teams:accept_invitation', args=[self.id]))

    class Meta:
        unique_together = ('team', 'email')

apps/teams/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from apps.teams.util import get_next_unique_team_slug
from .models import Team, Invitation


class TeamSignupForm(SignupForm):
    invitation_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    full_name = forms.CharField(
        label=_("Full name"),
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': _('Full name')}),
        required=False,
    )
    phone_number = forms.CharField(
        label=_("Phone Number"),
        max_length=15,
        widget=forms.TextInput(attrs={'placeholder': _('Phone Number')}),
        required=False,
    )
    company_name = forms.CharField(
        label=_("Company Name"),
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': _('Company Name')}),
        required=False,
    )
    mailsaas_type = forms.CharField(
        label=_("User Type"),
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': _('User Type')}),
        required=False,
    )
    
    def clean_team_name(self):
        full_name = self.cleaned_data['full_name']
        phone_number = self.cleaned_data['phone_number']
        company_name = self.cleaned_data['company_name']
        mailsaas_type = self.cleaned_data['mailsaas_type']
        invitation_id = self.cleaned_data.get('invitation_id')
        # if invitation is not set then team name is required
        if not invitation_id and not full_name:
            raise forms.ValidationError(_('Full Name is required!'))
        if not invitation_id and not phone_number:
             raise forms.ValidationError(_('Phone Number is required!'))
        if not invitation_id and not company_name:
             raise forms.ValidationError(_('Company Name is required!'))
        if not invitation_id and not mailsaas_type:
             raise forms.ValidationError(_('User Type is required!'))
        
        return full_name

    def clean_invitation_id(self):
        invitation_id = self.cleaned_data.get('invitation_id')
        if invitation_id:
            try:
                invite = Invitation.objects.get(id=invitation_id)
                if invite.is_accepted:
                    raise forms.ValidationError(_(
                        'It looks like that invitation link has expired. '
                        'Please request a new invitation or sign in to continue.'
                    ))
            except (Invitation.DoesNotExist, ValidationError):
                # ValidationError is raised if the ID isn't a valid UUID, which should be treated the same
                # as not found
                raise forms.ValidationError(_(
                    'That invitation could not be found. '
                    'Please double check your invitation link or sign in to continue.'
                ))
        return invitation_id

    def save(self, request):
        invitation_id = self.cleaned_data['invitation_id']
        full_name = self.cleaned_data['full_name']
        phone_number = self.cleaned_data['phone_number']
        company_name = self.cleaned_data['company_name']
        mailsaas_type = self.cleaned_data['mailsaas_type']

        print("reqqqqqqqq ",request, full_name)
        user = super().save(request)
        user.full_name = full_name
        user.phone_number = phone_number
        user.company_name = company_name
        user.mailsaas_type = mailsaas_type
        user.save()
        print("userrrrr ", user)

        if invitation_id:
            assert not full_name
        else:
            slug = get_next_unique_team_slug(full_name)
            team = Team.objects.create(name=full_name, slug=slug)
            team.members.add(user, through_defaults={'role': 'admin'})
            team.save()
        return user


class TeamChangeForm(forms.ModelForm):

    class Meta:
        model = Team
        fields = ('name', 'slug')

apps/teams/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_POST
from rest_framework import viewsets

from apps.teams.decorators import login_and_team_required, team_admin_required
from .invitations import send_invitation, process_invitation, clear_invite_from_session
# from .forms import TeamChangeForm
from .models import Team, Invitation
from .serializers import TeamSerializer, InvitationSerializer


@login_required
def manage_teams(request):
    return render(request, 'teams/teams.html', {})


@login_required
def list_teams(request):
    teams = request.user.teams.all()
    return render(request, 'teams/list_teams.html', {
        'teams': teams,
    })


@login_required
def create_team(request):
    if request.method == 'POST':
        form = TeamChangeForm(request.POST)
        if form.is_valid():
            team = form.save()
            team.members.add(request.user, through_defaults={'role': 'admin'})
            team.save()
            return HttpResponseRedirect(reverse('teams:list_teams'))
    else:
        form = TeamChangeForm()
    return render(request, 'teams/manage_team.html', {
        'form': form,
        'create': True,
    })


@login_and_team_required
def manage_team(request, team_slug):
    team = request.team
    if request.method == 'POST':
        form = TeamChangeForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teams:list_teams'))
    else:
        form = TeamChangeForm(instance=team)
    return render(request, 'teams/manage_team.html', {
        'team': team,
        'form': form,
    })


def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    if not invitation.is_accepted:
        # set invitation in the session in case needed later
        request.session['invitation_id'] = invitation_id
    else:
        clear_invite_from_session(request)
    return render(request, 'teams/accept_invite.html', {
        'invitation': invitation,
    })


@login_required
@require_POST
def accept_invitation_confirm(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    if invitation.is_accepted:
        messages.error(request, _('Sorry, it looks like that invitation link has expired.'))
        return HttpResponseRedirect(reverse('web:home'))
    else:
        process_invitation(invitation, request.user)
        clear_invite_from_session(request)
        messages.success(request, _('You successfully joined {}').format(invitation.team.name))
        return HttpResponseRedirect(reverse('web:team_home', args=[invitation.team.slug]))


class TeamViewSet(viewsets.ModelViewSet):
    queryset = Team.objects.all()
    serializer_class = TeamSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.teams.all()

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        team = serializer.save()
        team.members.add(self.request.user, through_defaults={'role': 'admin'})


class InvitationViewSet(viewsets.ModelViewSet):
    queryset = Invitation.objects.all()
    serializer_class = InvitationSerializer

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.queryset.filter(team__in=self.request.user.teams.all())

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        invitation = serializer.save(invited_by=self.request.user)
        send_invitation(invitation)


@team_admin_required
def resend_invitation(request, team, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    if invitation.team != request.team:
        raise ValueError(_('Request team {team} did not match invitation team {invite_team}').format(
            team=request.team.slug,
            invite_team=invitation.team.slug,
        ))
    send_invitation(invitation)
    return HttpResponse('Ok')

templates/teams/accept_invite.html
{% extends "web/base.html" %}
{% load static %}
{% load i18n %}
{% block body %}
<section class="section container">
    <div class="columns">
        <div class="column is-one-third">
            <img src="{% static 'images/undraw/undraw_lighthouse.svg' %}" alt="Welcome!">
        </div>
      {% if not invitation.is_accepted %}
        <div id="tagline" class="column">
            <h1 class="title is-size-2">Accept Invitation?</h1>
            <h2 class="subtitle is-size-4">
                You've been invited to join {{ invitation.team.name }}
                by {{ invitation.invited_by.get_display_name }}.
            </h2>
            {% if request.user.is_authenticated %}
              <form action="{% url 'teams:accept_invitation_confirm' invitation.id %}" method="post">
              {% csrf_token %}
            {% if request.user.email == invitation.email %}
              <input type="submit" class="button is-primary is-large" value="Accept Invitation" />
            {% else %}
                <p class="warning">
                     This invitation was sent to {{ invitation.email }} but you're logged in as {{ request.user.email }}.
                     What would you like to do?
                </p>
                <p class="buttons">
                  <input type="submit" class="button is-primary is-large" value="Accept as {{ request.user.email }}" />
                  <a class="button is-primary is-large is-outlined" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                    Sign out
                  </a>
                </p>
              {% endif %}
              </form>
            {% else %}
                <p class="buttons">
                    <a class="button is-primary is-large" href="{% url 'account_signup' %}?invitation_id={{ invitation.id }}">
                        Create Account to Accept
                    </a>
                </p>
            {% endif %}
        </div>
      {% else %}
        <div class="column" id="tagline">
          <h2 class="subtitle is-size-5">
            Sorry, it looks like that invitation has already been accepted or expired.
          </h2>
          <h2 class="subtitle is-size-5">
            If you think this is a mistake, ask your team administrator to invite you again!
          </h2>
      {% endif %}
    </div>
</section>
{% endblock %}

templates/teams/list_teams.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
{% if teams %}
<h1 class="title is-size-4">Your Teams</h1>
<table class="table is-striped is-fullwidth">
    <thead>
    <tr>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>
    {% for team in teams %}
    <tr>
        <td><a href="{% url 'teams:manage_team' team.slug %}">{{team.name}}</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a class="button is-primary is-outlined" href="{% url 'teams:create_team' %}">
    <span class="icon is-small"><i class="fa fa-plus"></i></span>
    <span>New Team</span>
</a>
{% else %}
<div id="dashboard-content">
    <div class="columns">
        <div class="column is-one-third">
            <img alt="Nothing Here" src="{% static 'images/undraw/undraw_team.svg' %}">
        </div>
        <div class="column is-two-thirds">
            <h1 class="title is-4">No Teams Yet!</h1>
            <h2 class="subtitle">Create your first team below to get started.</h2>
            <p>
                <a class="button is-primary" href="{% url 'teams:create_team' %}">
                    <span class="icon is-small"><i class="fa fa-plus"></i></span>
                    <span>Create Team</span>
                </a>
            </p>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/teams/manage_team.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% block app %}
<section class="app-card">
    <h1 class="title is-size-4">
        {% if create %}
            {% trans "Create Team" %}
        {% else %}
            {% trans "Edit Team Details" %}
        {% endif %}
    </h1>
    <form method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">{% trans "Name" %}</label>
          <div class="control">
            {{ form.name }}
          </div>
          {{ form.name.errors }}
        </div>
        <div class="field">
          <label class="label">{% trans "Team ID" %}</label>
          <div class="control">
            {{ form.slug }}
          </div>
          {{ form.slug.errors }}
        </div>
        <div class="field is-grouped">
            <div class="control">
                <input class="button is-primary" type="submit" value="{% trans 'Save' %}">
            </div>
        </div>
    </form>
</section>
{% if not create %}
    <div id="team-content"></div>
{% endif %}
{% endblock %}
{% block page_js %}
{# NOTE: the rest framework imports must precede the react bundle #}
<script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
<script src="{% url 'api_schemajs' %}"></script>
<script src="{% static 'js/teams-bundle.js' %}"></script>
{% endblock %}

templates/teams/teams.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% block app %}
  <div id="team-content"></div>
{% endblock %}
{% block page_js %}
{# NOTE: the rest framework imports must precede the react bundle #}
<script type="application/javascript">
    // initialize any page specific stuff here
    // static files that are used by the page javascript.
    var STATIC_FILES = {
        'undraw_team': "{% static 'images/undraw/undraw_team.svg' %}",
    };
    const inviteUrlTemplate = "{% url 'teams:resend_invitation' '__team_slug__' '__invite_id__' %}";
    const getInviteUrl = function (teamSlug, inviteId) {
      return inviteUrlTemplate.replace('__team_slug__', teamSlug).replace('__invite_id__', inviteId);
    };
</script>
<script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
<script src="{% url 'api_schemajs' %}"></script>
<script src="{% static 'js/teams-bundle.js' %}"></script>
{% endblock %}